services:
  supabase-minio:
    profiles:
    - local-storage-only

  minio-createbucket:
    profiles:
    - local-storage-only

  supabase-storage:
    depends_on: !override
      supabase-rest:
        condition: service_started
      imgproxy:
        condition: service_started
    environment:
    - SERVER_REGION=${REGION}
    - REGION=${REGION}
    - GLOBAL_S3_BUCKET=${GLOBAL_S3_BUCKET}
    - GLOBAL_S3_ENDPOINT=${GLOBAL_S3_ENDPOINT}
    - GLOBAL_S3_PROTOCOL=${GLOBAL_S3_PROTOCOL}
    - GLOBAL_S3_FORCE_PATH_STYLE=${GLOBAL_S3_FORCE_PATH_STYLE}
    - AWS_ACCESS_KEY_ID=${STORAGE_S3_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${STORAGE_S3_SECRET_ACCESS_KEY}
