import { afterAll, beforeAll, describe, test } from 'vitest'
import { config, requireAnonKey, requireServiceRoleKey } from '../src/env.js'
import { apiRequest, expectOk, pgQuery } from '../src/http.js'

describe('rest', () => {
  const table = `codex_rest_probe_${config.runId.replaceAll('-', '_')}`

  beforeAll(async () => {
    const service = requireServiceRoleKey()
    const query = [
      `create table public.${table} (id bigint generated by default as identity primary key, name text not null)`,
      `alter table public.${table} enable row level security`,
      `create policy ${table}_service_all on public.${table} for all to service_role using (true) with check (true)`,
      `notify pgrst, 'reload schema'`,
    ].join('; ')
    expectOk(await pgQuery(query, service), 'rest create probe table')
    await new Promise((resolve) => setTimeout(resolve, 1000))
  })

  afterAll(async () => {
    const service = requireServiceRoleKey()
    await pgQuery(`drop table if exists public.${table};`, service)
  })

  test('OpenAPI accepts anon and publishable keys', async () => {
    const anon = requireAnonKey()
    expectOk(await apiRequest('/rest/v1/', { key: anon }), 'rest openapi anon')

    if (config.publishableKey) {
      expectOk(await apiRequest('/rest/v1/', { key: config.publishableKey }), 'rest openapi publishable')
    }
  })

  test('service role can insert and select via PostgREST', async () => {
    const service = requireServiceRoleKey()
    expectOk(
      await apiRequest(`/rest/v1/${table}`, {
        method: 'POST',
        key: service,
        headers: { Prefer: 'return=representation' },
        json: { name: 'ok' },
      }),
      'rest insert service',
    )

    expectOk(
      await apiRequest(`/rest/v1/${table}?select=id,name`, {
        key: service,
      }),
      'rest select service',
    )
  })
})
